### PR TITLE
Add Database Provider Env Var

### PR DESCRIPTION
**Pull request by ElderMael**

### CODE REVIEW

**Comment by TheZoker** [comment]
Nice addition! That way we can use sqlite as database provider, right?

**Comment by ndom91** [comment]
> Nice addition! That way we can use sqlite as database provider, right?

Yeah you could more easily set that option now 👍

**Review by ndom91 — APPROVED** [review]
Sure why not! Does make it a bit easier for people wanting to use something else. Especially in docker setups. 

Nice change

**Review by ndom91 — APPROVED** [review]

**Comment by ndom91** [comment]
Unfortunately I'll have to revert this. Prisma explicitly doesn't support this apparently :( 

image

See: https://github.com/prisma/prisma/issues/998

**Pull request merged**
